"""adding new column to routines table storing sets and repitions of exercises

Revision ID: 3e4aaad529eb
Revises: ccc868cb8620
Create Date: 2023-11-21 15:15:57.496947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4aaad529eb'
down_revision = 'ccc868cb8620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets_n_Reps', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('sets_n_Reps')

    # ### end Alembic commands ###
